version: '3'
services:
  postgres:
    image: 'postgres:14'
    ports:
      - '5432:5432'
    restart: unless-stopped
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: password
      POSTGRES_DB: go_movies
    volumes:
      - './db-data/postgres/:/var/lib/postgresql/data'